POSTGRES_SQL_USERNAME: postgres
POSTGRES_SQL_PASSWORD: 2373
POSTGRES_SQL_HOST: localhost
POSTGRES_SQL_PORT: 5432
POSTGRES_SQL_DB: email_send

SERVER_PORT: 9000
ACTIVE_PROFILE: dev

#Email Config
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: hvjjj83@gmail.com
EMAIL_PASSWORD: wsnw wbyq mddz tgll
VERIFY_EMAIL_HOST: http://localhost:${SERVER_PORT}